AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./search-photos-copy
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::134260679325:role/service-role/codebuild-lambdaBuildProject-HW2-service-role'
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos-copy
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::134260679325:role/service-role/codebuild-lambdaBuildProject-HW2-service-role'
      Environment:
        Variables:
          REGION: us-east-1
