AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Lambda for Searchable Photo Library
Resources:
  SearchPhotosLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./search-photos-copy
      Description: "Lambda for searching photos"
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::134260679325:role/CloudFormationRole'
      Environment:
        Variables:
          REGION: us-east-1
  IndexPhotosLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos-copy
      Description: "Lambda for indexing photos"
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::134260679325:role/CloudFormationRole'
      Environment:
        Variables:
          REGION: us-east-1
